# Generated by Django 5.1.3 on 2024-11-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pdf_file', models.CharField(max_length=255)),
                ('image_folder_path', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('released_year', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'catalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorited',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('catalog_id', models.IntegerField()),
            ],
            options={
                'db_table': 'favorited',
                'managed': False,
            },
        ),
    ]
